# Generated by Django 4.2 on 2023-04-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titties', models.CharField(max_length=60)),
                ('content', models.CharField(max_length=120)),
                ('chat_time', models.DateTimeField(blank=True, default='2023-04-13 16:45:12', null=True)),
            ],
        ),
    ]
